# Generated by Django 2.0.13 on 2019-06-17 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='subTask',
            fields=[
                ('subtask_id', models.AutoField(primary_key=True, serialize=False)),
                ('subtask_name', models.CharField(max_length=200)),
                ('subtask_description', models.TextField()),
                ('subtask_assign_to', models.IntegerField()),
                ('subtask_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtask_published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_assign_to', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='subtask_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamify.Task'),
        ),
    ]
