# Generated by Django 2.0.13 on 2019-06-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_creator',
            field=models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='teamify.Task'),
        ),
    ]
