# Generated by Django 2.0.13 on 2019-06-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamify', '0002_auto_20190617_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='subtask_published_date',
        ),
    ]
