# Generated by Django 2.0.13 on 2019-06-19 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamify', '0004_auto_20190620_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_assign_to',
            field=models.ForeignKey(db_column='subtask_assign_to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
